### ISSUE TITLE
HTTPS doesn't seem to be supported

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j-contrib/neo4j-elasticsearch#18]
It seems to go to the `/_nodes/_all/http` path just fine but then it switches to `http` and the ip address.  I've tried setting `host`, `publish_host`, and `bind_host` in the `elasticsearch.yml`.  Looking into it now, but I'm not yet sure if it's this plugin or Jest.

Some example output from Neo4j:

```
02:52:49.894 [NodeChecker RUNNING] DEBUG i.s.client.http.JestHttpClient - Request method=GET url=https://elastic-brian.thedomain.com:9200/_nodes/_all/http
02:52:50.822 [NodeChecker RUNNING] DEBUG io.searchbox.action.AbstractAction - Request and operation succeeded
02:52:50.839 [NodeChecker RUNNING] INFO  i.s.c.config.discovery.NodeChecker - Discovered 1 HTTP hosts: http://24.245.13.14:9200
02:52:50.839 [NodeChecker RUNNING] DEBUG i.s.client.AbstractJestClient - Server pool was updated to contain 1 servers.
2016-03-25 02:52:53.501+0000 INFO  Successfully started database
2016-03-25 02:52:53.568+0000 INFO  Starting HTTP on port 7474 (1 threads available)
2016-03-25 02:52:53.970+0000 INFO  Enabling HTTPS on port 7473
2016-03-25 02:52:54.100+0000 INFO  Mounting static content at /webadmin
2016-03-25 02:52:54.138+0000 INFO  Mounting static content at /browser
2016-03-25 02:52:55.788+0000 INFO  Remote interface ready and available at http://0.0.0.0:7474/
02:53:09.492 [qtp1923473655-31] DEBUG i.s.client.http.JestHttpClient - POST method created based on client request
02:53:09.495 [qtp1923473655-31] DEBUG i.s.client.http.JestHttpClient - Request method=POST url=http://24.245.13.14:9200/_bulk
02:53:09.574 [I/O dispatcher 1] ERROR i.s.client.http.JestHttpClient - Exception occurred during async execution.
org.apache.http.ConnectionClosedException: Connection closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:341) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:263) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [httpasyncclient-4.1.1.jar:4.1.1]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [httpasyncclient-4.1.1.jar:4.1.1]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:116) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106) [httpcore-nio-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590) [httpcore-nio-4.4.4.jar:4.4.4]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
2016-03-25 02:53:09.579+0000 WARN  Problem Updating ElasticSearch  Connection closed
org.apache.http.ConnectionClosedException: Connection closed
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:341)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:263)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:116)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jexp** [comment]
Are you using ES 2?

Von meinem iPhone gesendet

**Comment by cheerfulstoic** [comment]
Yeah, using 2.2.1 (latest version)
