### ISSUE TITLE
neo4j 3.1.1 which version of jar to use?

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/neo4j-elasticsearch#41]
I'm using neo4j 3.1.1, but when I tried to use neo4j elastic search jar of 3.1.4, I encounter below error (neo4j doesnt start when i copied the jar files there)

```
2017-07-23 14:36:56.012+0000 INFO  Starting...
2017-07-23 14:37:04.797+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@611efae4' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@611efae4' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@611efae4' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@611efae4' was successfully initialized, but failed to start. Please see attached cause exception.
```

**Comment by adinu** [comment]
hi, did you find any solution for this?

**Comment by jexp** [comment]
There is a 3.1 branch that you can use.
