### ISSUE TITLE
Unable to start neo4j service after stop after adding jar in plugins folder

### ISSUE THREAD

**Issue by siddharth-gitrepo** [neo4j-contrib/neo4j-elasticsearch#50]
Hi,
I am using Neo4J version 3.4.4 and elasticsearch 6.3.2.

I have copied the neo4j-elasticsearch-3.2.3 jar file to plugins folder and attempted to restart/stop-start the service.
I get the below error in neo4j console.
elasticsearch is up and running.

Error logs:
C:\neo4j-community-3.4.4-windows\neo4j-community-3.4.4>neo4j console
2018-08-14 05:59:49.479+0000 INFO  ======== Neo4j 3.4.4 ========
2018-08-14 05:59:49.507+0000 INFO  Starting...
2018-08-14 05:59:50.384+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@638ef7ed' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@638ef7ed' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@638ef7ed' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@638ef7ed' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\neo4j-community-3.4.4-windows\neo4j-community-3.4.4\data\databases\graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:212)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:125)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@18317edc' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/BaseSetting;
        at org.neo4j.elasticsearch.ElasticSearchKernelExtensionFactory$ElasticSearchSettings.<clinit>(ElasticSearchKernelExtensionFactory.java:24)
        at org.neo4j.elasticsearch.ElasticSearchKernelExtensionFactory.newInstance(ElasticSearchKernelExtensionFactory.java:40)
        at org.neo4j.elasticsearch.ElasticSearchKernelExtensionFactory.newInstance(ElasticSearchKernelExtensionFactory.java:18)
        at org.neo4j.kernel.extension.KernelExtensions.newInstance(KernelExtensions.java:78)
        at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:61)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
        ... 12 more
2018-08-14 05:59:50.392+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by jexp** [comment]
You need to use the 3.4. branch.

For a proper elastic search integration I recommend to check out the GraphAware one: https://dzone.com/refcardz/graph-powered-search-neo4j-amp-elasticsearch?chapter=1
