### ISSUE TITLE
neo4j Elasticsearch failed to initialize

### ISSUE THREAD

**Issue by satya06** [neo4j-contrib/neo4j-elasticsearch#51]
Starting Neo4j.
2018-09-04 08:17:16.867+0000 INFO  ======== Neo4j 3.0.12 ========
2018-09-04 08:17:16.886+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2018-09-04 08:17:17.280+0000 INFO  Starting...
2018-09-04 08:17:17.721+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2018-09-04 08:17:17.741+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@352ddc7e' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@352ddc7e' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@352ddc7e' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@352ddc7e' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:190)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:55)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.elasticsearch.ElasticSearchExtension@1ad38216' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:80)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: io/searchbox/client/JestClientFactory
	at org.neo4j.elasticsearch.ElasticSearchExtension.getJestClient(ElasticSearchExtension.java:63)
	at org.neo4j.elasticsearch.ElasticSearchExtension.init(ElasticSearchExtension.java:48)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 16 more
Caused by: java.lang.ClassNotFoundException: io.searchbox.client.JestClientFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

**Comment by jexp** [comment]
You have a horribly old Neo4j version. Please update.

**Comment by jexp** [comment]
There are a few releases that you can use directly otherwise check out the appropriate branch and run `mvn package` and use the large jar.

**Comment by satya06** [comment]
Thank it is working
