### ISSUE TITLE
Neo4j 3.4.9 Elasticsearch 5.4.0 configuration Issue

### ISSUE THREAD

**Issue by VenkataMR** [neo4j-contrib/neo4j-elasticsearch#52]
Configuring Neo4j 3.4.9 community edition with Elasticsearch 5.4.0 not working. Below are the configuration details
copied following jar to NEO4J_HOME/plugins 
```
avalon-framework-4.1.5.jar
commons-logging-1.2.jar
jms-1.1.jar
log4j-1.2.17.jar
logkit-2.0.jar
mail-1.4.1.jar
neo4j-elasticsearch-3.4.5.jar
slf4j-log4j12-1.7.24.jar
```

Added below properties to neo4j.conf directory
```
elasticsearch.host_name=http://127.0.0.1:9200
elasticsearch.index_spec=content:Content(contentId,contentName)
elasticsearch.discovery=true

```
Started Elasticsearch and Neo4j.
There are no exceptions/error in neo4j debug.log
Below is the log trace when started neo4j.

```
2018-12-21 08:27:14.735+0000 INFO  ======== Neo4j 3.4.9 ========
2018-12-21 08:27:14.767+0000 INFO  Starting...
INFO  - 2018-12-21 13:57:16.501; io.searchbox.client.AbstractJestClient; Setting server pool to a list of 1 servers: [http://127.0.0.1:9200]
INFO  - 2018-12-21 13:57:16.501; io.searchbox.client.JestClientFactory; Using multi thread/connection supporting pooling connection manager
INFO  - 2018-12-21 13:57:16.611; io.searchbox.client.JestClientFactory; Using default GSON instance
INFO  - 2018-12-21 13:57:16.611; io.searchbox.client.JestClientFactory; Node Discovery enabled...
INFO  - 2018-12-21 13:57:16.642; io.searchbox.client.JestClientFactory; Idle connection reaping disabled...
INFO  - 2018-12-21 13:57:16.751; io.searchbox.client.AbstractJestClient; Setting server pool to a list of 0 servers: []
WARN  - 2018-12-21 13:57:16.751; io.searchbox.client.AbstractJestClient; No servers are currently available to connect.
2018-12-21 08:27:19.158+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-12-21 08:27:22.939+0000 INFO  Started.
2018-12-21 08:27:23.924+0000 INFO  Remote interface available at http://localhost:7474/
ERROR - 2018-12-21 13:58:16.758; io.searchbox.client.config.discovery.NodeChecker; Error executing NodesInfo!
io.searchbox.client.config.exception.NoServerConfiguredException: No Server is assigned to client to connect
        at io.searchbox.client.AbstractJestClient$ServerPool.getNextServer(AbstractJestClient.java:132)
        at io.searchbox.client.AbstractJestClient.getNextServer(AbstractJestClient.java:81)
        at io.searchbox.client.http.JestHttpClient.prepareRequest(JestHttpClient.java:80)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:46)
        at io.searchbox.client.config.discovery.NodeChecker.runOneIteration(NodeChecker.java:65)
        at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:189)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by jexp** [comment]
Is your ES running on localhost?

if you look at this it doesn't seem to find it:

```
INFO  - 2018-12-21 13:57:16.501; io.searchbox.client.AbstractJestClient; Setting server pool to a list of 1 servers: [http://127.0.0.1:9200]
INFO  - 2018-12-21 13:57:16.611; io.searchbox.client.JestClientFactory; Node Discovery enabled...
INFO  - 2018-12-21 13:57:16.751; io.searchbox.client.AbstractJestClient; Setting server pool to a list of 0 servers: []
WARN  - 2018-12-21 13:57:16.751; io.searchbox.client.AbstractJestClient; No servers are currently available to connect.
```
