### ISSUE TITLE
Newly compiled elastic plugin jar breaks Neo4j (3.5.5)

### ISSUE THREAD

**Issue by arikan** [neo4j-contrib/neo4j-elasticsearch#58]
Hi there, 

I cloned branch 3.4.

Changed the pom.xml to version 3.5.5 to make it work with our current Neo4j.
```
<version>3.5.5</version>
```

Successfully compiled and packaged:

```
mvn clean install -DskipTests
```

Copied the packaged `neo4j-elasticsearch-3.5.5.jar` file into Neo4j plugins directory. 

Started Neo4j and got the error below, any help would be appreciated.

```
2020-02-23 20:12:22.455+0000 INFO  ======== Neo4j 3.5.5 ========
2020-02-23 20:12:22.470+0000 INFO  Starting...
2020-02-23 20:12:23.671+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65fe9e33' was successfully initialized, but failed to start. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65fe9e33' was successfully initialized, but failed to start. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65fe9e33' was successfully initialized, but failed to start. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:123)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
	at com.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@65fe9e33' was successfully initialized, but failed to start. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /Users/arikan/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-4a52d26d-7e7c-4c60-bbd5-b90ea4b87722/installation-3.5.5/data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:229)
	at com.neo4j.commercial.edition.CommercialGraphDatabase.<init>(CommercialGraphDatabase.java:20)
	at com.neo4j.server.database.CommercialGraphFactory.newGraphDatabase(CommercialGraphFactory.java:40)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalKernelExtensions@13518f37' failed to initialize. Please see the attached cause exception "No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:434)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:66)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:102)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:224)
	... 9 more
Caused by: org.neo4j.kernel.extension.FailedToBuildKernelExtensionException: Failed to build kernel extension KernelExtension:ElasticSearchKernelExtensionFactory[ELASTIC_SEARCH] due to a missing dependency: No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService
	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.wrap(KernelExtensionFailureStrategies.java:35)
	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies.access$000(KernelExtensionFailureStrategies.java:26)
	at org.neo4j.kernel.extension.KernelExtensionFailureStrategies$1.handle(KernelExtensionFailureStrategies.java:70)
	at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:68)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:413)
	... 12 more
Caused by: org.neo4j.kernel.impl.util.UnsatisfiedDependencyException: No dependency satisfies type interface org.neo4j.graphdb.GraphDatabaseService
	at org.neo4j.kernel.impl.util.Dependencies.resolveDependency(Dependencies.java:66)
	at org.neo4j.graphdb.DependencyResolver$Adapter.resolveDependency(DependencyResolver.java:145)
	at org.neo4j.kernel.impl.util.DependenciesProxy$ProxyHandler.invoke(DependenciesProxy.java:80)
	at com.sun.proxy.$Proxy23.getGraphDatabaseService(Unknown Source)
	at org.neo4j.elasticsearch.ElasticSearchKernelExtensionFactory.newInstance(ElasticSearchKernelExtensionFactory.java:40)
	at org.neo4j.elasticsearch.ElasticSearchKernelExtensionFactory.newInstance(ElasticSearchKernelExtensionFactory.java:18)
	at org.neo4j.kernel.extension.AbstractKernelExtensions.newInstance(AbstractKernelExtensions.java:120)
	at org.neo4j.kernel.extension.AbstractKernelExtensions.init(AbstractKernelExtensions.java:62)
	... 13 more
2020-02-23 20:12:23.672+0000 INFO  Neo4j Server shutdown initiated by request
```

**Comment by arikan** [comment]
This issue was fixed when I clone NOT the branch 3.4 but the tag 3.5.6 https://github.com/neo4j-contrib/neo4j-elasticsearch/tree/3.5.6

It would be great to merge it to the master @jexp
